// 導覽與切換互動；一般內容請改 content.js。
const { stages, tables, domains } = window.PORTFOLIO_DATA;
function el(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node}
function setStage(index){const data=stages[index],tabs=document.querySelectorAll('.stage-tab'),panel=document.getElementById('stage-detail');tabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1});panel.replaceChildren();panel.setAttribute('aria-labelledby',`stage-${index}`);panel.append(el('span','detail-code',data.code),el('h3','',data.title),el('p','',data.description));const tags=el('div','detail-tags');data.tags.forEach(t=>tags.append(el('span','',t)));panel.append(tags)}
function setTable(index){const data=tables[index],buttons=document.querySelectorAll('.table-item'),panel=document.getElementById('table-detail');buttons.forEach((button,i)=>button.setAttribute('aria-pressed',String(i===index)));panel.replaceChildren();panel.append(el('span','small-label','TABLE / '+String(index+1).padStart(2,'0')),el('h3','',data.name),el('span','row-count',`${data.rows} 筆模擬資料`));const fields=el('div','fields');data.fields.forEach(f=>fields.append(el('span','',f)));panel.append(fields,el('p','relations',data.relation))}
function setDomain(index){const data=domains[index],tabs=document.querySelectorAll('.view-tab'),panel=document.getElementById('domain-content');tabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1});panel.setAttribute('aria-labelledby',`domain-${index}`);panel.replaceChildren();const story=el('div','domain-story');story.append(el('span','panel-label',data.label+' / ANALYSIS'),el('h3','',data.title),el('p','',data.description));const questions=el('ul','questions');data.questions.forEach(q=>questions.append(el('li','',q)));story.append(questions);const numbers=el('div','domain-numbers'),pair=el('div','number-pair');data.metrics.forEach(([number,label])=>{const tile=el('div','number-tile');tile.append(el('span','','PROJECT DATA'),el('strong','',number),el('small','',label));pair.append(tile)});numbers.append(pair,el('p','domain-caption',data.caption));panel.append(story,numbers)}
function wireTabs(container,selector,onSelect){container.addEventListener('keydown',event=>{if(!['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...container.querySelectorAll(selector)],current=tabs.indexOf(document.activeElement);let next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(current+(event.key==='ArrowRight'||event.key==='ArrowDown'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();onSelect(next)})}
const stageTabs=document.getElementById('stage-tabs');stages.forEach((data,i)=>{const button=el('button','stage-tab');button.type='button';button.id=`stage-${i}`;button.role='tab';button.setAttribute('aria-controls','stage-detail');button.append(el('span','num',data.number),el('strong','',data.title),el('span','arrow','↗'));button.addEventListener('click',()=>setStage(i));stageTabs.append(button)});wireTabs(stageTabs,'.stage-tab',setStage);setStage(0);
const tableList=document.getElementById('table-list');tables.forEach((data,i)=>{const button=el('button','table-item');button.type='button';button.append(el('strong','',data.name),el('small','',`${data.rows} rows`));button.addEventListener('click',()=>setTable(i));tableList.append(button)});setTable(0);
const domainTabs=document.getElementById('domain-tabs');domains.forEach((data,i)=>{const button=el('button','view-tab',data.name);button.type='button';button.id=`domain-${i}`;button.role='tab';button.setAttribute('aria-controls','domain-content');button.addEventListener('click',()=>setDomain(i));domainTabs.append(button)});wireTabs(domainTabs,'.view-tab',setDomain);setDomain(0);
document.getElementById('year').textContent=new Date().getFullYear();
